name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          majorList: major
          minorList: minor,feat,feature
          patchList: patch,fix,chore
          patchAll: true
          skipInvalidTags: true
          token: ${{ github.token }}
          branch: master

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          commit: master
