name: Release

on:
  push:
    branches:
      - publicise-repo
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Get Next Version
      #   id: semver
      #   uses: ietf-tools/semver-action@v1
      #   with:
      #     majorList: major
      #     minorList: feat,feature
      #     patchAll: true
      #     skipInvalidTags: true
      #     token: ${{ github.token }}
      #     branch: main

      # - name: Create Release
      #   uses: ncipollo/release-action@v1.12.0
      #   with:
      #     allowUpdates: true
      #     draft: false
      #     makeLatest: true
      #     name: ${{ steps.semver.outputs.next }}
      #     token: ${{ github.token }}
