name: Terraform Docs Azure

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/terraform-docs-azure.yml
      - 'azure/**'

jobs:
  generate:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: List Modules
        id: list
        run: |
          modules=$(make list-modules CLOUD_PROVIDER=azure)
          echo modules=$modules >> $GITHUB_OUTPUT

      - name: Check Module Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ${{ steps.list.outputs.modules }}
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
          git-push: "true"
