name: Terraform Documentation

on:
  push:
    branches:
      - master
      - generate-documentation
    paths:
      - .github/workflows/terraform-docs.yml
      - 'modules/**'
      - docs

permissions:
  contents: 'read'
  pull-requests: 'write'
  id-token: 'write'

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Question docs
        id: question-docs
        run: |
          echo "EXIT_CODE=$(make -q -s docs; echo $?)" >> $GITHUB_OUTPUT

      - name: Run if updated
        if: ${{ steps.question-docs.outputs.EXIT_CODE != 0 }}
        run: |
          echo "Commit new docs"