name: Terraform Documentation

on:
  push:
    branches:
      - master
      - generate-documentation
    paths:
      - .github/workflows/terraform-docs.yml
      - 'modules/**'
      - docs

permissions:
  contents: 'write'
  pull-requests: 'write'

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Question docs
        id: question-docs
        run: |
          echo "EXIT_CODE=$(make -q -s docs; echo $?)" >> $GITHUB_OUTPUT

      - name: Build docs
        id: build-docs
        if: ${{ steps.question-docs.outputs.EXIT_CODE != 0 }}
        run: |
          make docs

      - name: Create PR
        id: create-pull-request
        if: ${{ steps.build-docs.outcome == 'success' }}
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update terraform documentation
          commit-message: Update terraform documentation
          author: GitHub <noreply@github.com>
          branch: fix/terraform-docs

      - name: Approve PR
        if: ${{ steps.build-docs.outcome == 'success' }}
        env:
          PR_URL: ${{ steps.create-pull-request.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr review --approve "$PR_URL"

      - name: Merge PR
        if: ${{ steps.build-docs.outcome == 'success' }}
        env:
          PR_URL: ${{ steps.create-pull-request.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --merge "$PR_URL"