name: Terraform Documentation

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/terraform-docs.yml
      - 'azure/**'
      - docs

jobs:
  generate:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: ./azure
          output-file: README.md
          output-method: inject
          git-push: "true"
